apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: stable-diffusion-cd
description: main application pipeline
serialPipeline:
 stages:
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
gke:
 cluster: projects/cliu201/locations/us-east1-b/clusters/sdspot